### ISSUE TITLE
Should be moved to the template

### ISSUE THREAD

**Issue by Wortex** [lautaroangelico/WebEngine#17]
https://github.com/lautaroangelico/WebEngine/blob/5cc818754d46791ed981d83f1662ee8b2445168a/includes/webengine.php#L127

I honestly think that this error shouldn't be hardcoded, but moved to a specific file in the template.

**Comment by lautaroangelico** [comment]
That would be counter productive since this is something that is triggered at the core level of the CMS and not the template handler. It's simply a bar to make sure the admin knows the website is currently offline and pushes the whole template down. Moving it to the template would require those who integrate templates to WebEngine to insert a piece of code to check for the same condition, there's no point on doing that for something that is barely used.

**Comment by Wortex** [comment]
True, but in general, styling and html should be controlled by the template.
