### ISSUE TITLE
Tela de downloads nao carrega

### ISSUE THREAD

**Issue by mandeerson** [lautaroangelico/WebEngine#60]
Para quem estiver com problema na tela de downloads nao carregar, tem um bug no codigo que pode ser resolvido fazendo a seguinte alteração.

Acesse a pasta Modules.
Abra o arquivo downloads.php

Procure pelas seguintes variáveis:

`$downloadCLIENTS = '';
$downloadPATCHES = '';
$downloadTOOLS = '';`

Altere para:

`$downloadCLIENTS = [];
$downloadPATCHES = [];
$downloadTOOLS = [];`

Salve o arquivo.

A tela de downloads passara a mostrar a lista de arquivos para download.

**Comment by lautaroangelico** [comment]
@mandeerson This was fixed in 1.2.5. You don't need the variables to be an array, as the web has a check in that same file to check if the different variables are an array or not.
https://github.com/lautaroangelico/WebEngine/blob/master/modules/downloads.php#L42

If they are not an array, the category is not displayed.
